---
title: "Wu_Yanan_lab3"
author: "WuYanan"
date: "September 29, 2017"
output: html_document
---

#Question 1
```{r}
library(MASS)
car <- Cars93
set.seed(1)

training <- sample(row.names(car),40,replace = FALSE)
train <- car[training,]
train
data <- as.numeric(row.names(train))
test <- car[-data,]
test

write.csv(train, file = "D:/R/Lab3/train.csv")
r.train <- read.csv("train.csv")
nonusa <- r.train[r.train$Origin == "non-USA",]
dim(nonusa)
usa <- r.train[r.train$Origin == "USA",]
dim(usa)
```

#Question 2
```{r}
ten <- sample(c("boy", "girl"),size = 10,replace = TRUE,prob = c(0.515,0.485))
ten
boy.ten <- sum(ten == "boy")
boy.ten
girl.ten <- sum(ten == "girl")
girl.ten
thousand <- sample(c("boy", "girl"), size = 10000, replace = TRUE, prob = c(0.515,0.485))
boy.thousand <- sum(thousand == "boy")
boy.thousand
girl.thousand <- sum(thousand == "girl")
girl.thousand
```

# Question 3
```{r}
three.boy <- dbinom(0:3, size = 10, prob = 0.515)
plot(0:3, three.boy)

eight.boy <- pbinom(8:10, size = 10, prob = 0.485,lower.tail = FALSE)
plot(8:10, eight.boy)
```

# Question 4
```{r}
dpois(4, lambda = 5)
ppois(5, lambda = 5, lower.tail = FALSE)
a <- dpois(0:20, lambda = 5)
plot(0:20,a,type = "b",pch = 18, col = "pink")
```